/*
// 1995Nov16 Scott  Redid most of the RSET* error reporting.
// 1995Apr06 Scott  First version.
//=====================================================================
//
// Filename: ..\HDP\LIB\SRC\HDP_ERR.H
//
//                  Copyright (C) 1999 by Foresight Imaging, LLC
//                                    All rights (world-wide) reserved.
//=====================================================================
*/

#ifndef _HDP_ERR_INC
#define _HDP_ERR_INC

/*
//  See file HDPERROR.DAT for a description of each error.
*/
#define HPERR_NO_VXD           500
#define HPERR_BAD_ERR_REV      501
#define HPERR_PARAM            502
#define HPERR_HANDLE           503
#define HPERR_EECORRUPT        504
#define HPERR_EEWRITE          505
#define HPERR_CLOSENEST        506
#define HPERR_CLOSE            507
#define HPERR_CHP_READ         508
#define HPERR_CHP_EOF          509
#define HPERR_CHP_SYNTAX       510
#define HPERR_CHP_TAG          511
#define HPERR_CHP_HEXPT        512
#define HPERR_CHP_JUNK         513
#define HPERR_CHP_SYMBOL       514
#define HPERR_TIMEOUT          515
#define HPERR_NO_BOARDS        516
#define HPERR_NO_RSET	         517

#define HPERR_RSETV_           520
#define HPERR_RSETV_VCHAN      520
#define HPERR_RSETV_CSYNC      521
#define HPERR_RSETV_PCLOCK     522
// Jack 08-15-08...
//#define HPERR_RSETV_RESV0
//#define HPERR_RSETV_RESV1
#define HPERR_RSETV_CLAMPPLAC  523
#define HPERR_RSETV_CLAMPDUR   524
// ...Jack 08-15-08
#define HPERR_RSETV_VTOTAL     525
#define HPERR_RSETV_FR_MSEC    526
#define HPERR_RSETV_INTERLACE  527
#define HPERR_RSETV_VSTYPE     528
#define HPERR_RSETV_VBP        529
#define HPERR_RSETV_HEIGHT     530
#define HPERR_RSETV_RESV2
#define HPERR_RSETV_RESV3
#define HPERR_RSETV_HFREQ      533
#define HPERR_RSETV_HTOTAL     534
#define HPERR_RSETV_HBS        535
#define HPERR_RSETV_WIDTH      536
#define HPERR_RSETV_HS_NSEC    537
#define HPERR_RSETV_HBP        538
#define HPERR_RSETV_RESV4
#define HPERR_RSETV_GAIN       540
#define HPERR_RSETV_BLEVEL     541
#define HPERR_RSETV_BLACKREF   542
#define HPERR_RSETV_WHITEREF   543
#define HPERR_RSETV_PIXSET10   544
#define HPERR_RSETV_PIXELSET   545
#define HPERR_RSETV_ZOOMDOWN   546
#define HPERR_RSETV_RESV5
#define HPERR_RSETV_BLANKFIL   548
#define HPERR_RSETV_PITCH      549
#define HPERR_RSETV_PASSMODE   550
#define HPERR_RSETV_DPDELAY    551
#define HPERR_RSETV_PHASE2     552
#define HPERR_RSETV_PHASE      553
#define HPERR_RSETV_VATTR      554
#define HPERR_RSETV_CONTROL    555
#define HPERR_RSETV_HSTART     557
#define HPERR_RSETV_VSTART     558
#define HPERR_RSETV_CAMCTL     559
#define HPERR_RSETV_REFPROG    560
#define HPERR_RSETV_REFBTYPE   561
#define HPERR_RSETV_REFBOARD   562
#define HPERR_RSETV_REF_MPAL   563
#define HPERR_RSETV_GAMMA      564
#define HPERR_RSETV_SYNCFILTER 565
#define HPERR_RSETV_PIXFREQ    566
#define HPERR_RSETV_VERTFREQ   567
#define HPERR_RSETV_RESV59     579

#define HPERR_RSET_MAINSET     580
#define HPERR_RSET_NEEDMAIN    581
#define HPERR_RSETS_PFREQ      582
#define HPERR_RSETD_PFREQ      583
#define HPERR_RSETS_HTOT       584
#define HPERR_RSETD_HTOT       585
#define HPERR_RSET_ODD_ILACE   586
#define HPERR_RSET_ZWIDTH      587
#define HPERR_RSET_ZHEIGHT     588
#define HPERR_RSET_HEND        589
#define HPERR_RSET_VEND        590
#define HPERR_RSET_HBPTIME     591

#define HPERR_PHASE_RANGE      601
#define HPERR_TOPLEFT_VALUES   602
#define HPERR_GAIN_RANGE       603
#define HPERR_BWREF_VALUES     604
#define HPERR_PIXELSET_RANGE   605
#define HPERR_BLEVEL_RANGE     606
#define HPERR_CHANNEL_RANGE    607
#define HPERR_SYNCFILTER_RANGE 608
#define HPERR_COMMAND_READY    610
#define HPERR_COMMAND_DONE     611
#define HPERR_COMMAND_CODE     612
#define HPERR_ODD_FB_ALIGN     613
#define HPERR_FG_LINE_LIMIT    614
#define HPERR_EEDATACHECK      615
#define HPERR_FILEP_PARAM      616
#define HPERR_ENCODE_REG       617
#define HPERR_CONT_DP_LIB      618
#define HPERR_CONTINUOUS_DP    619
#define HPERR_PHASE0_MIN       620
#define HPERR_PHASE0_MAX       621
#define HPERR_PHASE1_MIN       622
#define HPERR_PHASE1_MAX       623
#define HPERR_CSYNC_AWAY       624
#define HPERR_MEMORY_ALLOC     625
#define HPERR_USING_IHANDLES   626
#define HPERR_NOCURRENT_1PASS  627
#define HPERR_FAULT            628
#define HPERR_PIXEL_TYPE       629
#define HPERR_IMAGE_BOUNDS     630
#define HPERR_BOARDFEATURE     631
#define HPERR_NOT_IMPLEMENTED  632
#define HPERR_SYNC_RSET        633
#define HPERR_ISERIES          634

#define HPERR_INITIALIZING_INTS   635
#define HPERR_UNKNOWN_DRIVER_FCTN 636
#define HPERR_DEVICE_NOT_FOUND 637
#define HPERR_BIOS_NOT_FOUND   638
#define HPERR_NOT_OPEN         639
#define HPERR_NOT_FOUND        640
#define HPERR_READING_REGISTRY 641
#define HPERR_ABO_NOT_ASYNC    642
#define HPERR_ABO_ASYNC        643
#define HPERR_ABO_QUEUED       644
#define HPERR_ABO_ON_HOLD      645
#define HPERR_ABO_SCHEDULED    646
#define HPERR_ABO_RUNNING      647
#define HPERR_ABO_CANCELED     648
#define HPERR_ABO_COMPLETED    649
#define HPERR_ABO_FAILED       650
#define HPERR_ABO_EXPIRED      651
#define HPERR_NOT_ON_HOLD      652
#define HPERR_INITFAILED       653
#define HPERR_NOSSTRACKING     654
#define HPERR_BOARDSVARY       655
#define HPERR_SYNCSRCVARY      656
#define HPERR_IHCONFLICT       657
#define HPERR_GATEFILEDATA     658
#define HPERR_MEMORY_LOCK      659
#define HPERR_MAX_STREAM_IN_PROGRESS 660
#define HPERR_BUFFER_LOCK      661
#define HPERR_TOO_MANY_DESCRIPTORS 662
#define HPERR_FUNCTION_DEPRECATED 663
#define HPERR_BOARD_DOES_NOT_SUPPORT_STREAMING 664
#define HPERR_BOARD_DOES_NOT_SUPPORT_COMPRESSION 665
#define HPERR_COMPRESSION_IN_PROGRESS 666
#define HPERR_COMPRESSION_FILE 667
#define HPERR_COMPRESSION_INIT_FAILED 668
#define HPERR_COMPRESSION_START_FAILED 669
#define HPERR_COMPRESSION_FIRMWARE_FILE 670
#define HPERR_GATEFILECHANGED     671
/*
// Error codes for the IDEA Tools Library.
*/
#define HPERR_TOOL_SEQUENCE         800
#define HPERR_TOOL_RSETVIDEO        801
#define HPERR_TOOL_RSETCSYNC        802
#define HPERR_TOOL_RSETHTOT1        803
#define HPERR_TOOL_RSETPFREQ        804
#define HPERR_TOOL_DLL_REV          805
#define HPERR_TOOL_DLL_DATE         806
#define HPERR_TOOL_STOPPED          810
/*
// IDEA Auto-SYNC Channel Elimination Codes.
*/
#define HPERR_ASCHAN_VID_NOSYNCS    820
#define HPERR_ASCHAN_VID_SILENT_HI  821
#define HPERR_ASCHAN_VID_SILENT_LO  822
#define HPERR_ASCHAN_VID_MISSING    823
#define HPERR_ASCHAN_VID_ERRATIC    824
#define HPERR_ASCHAN_VID_SCANT      825
#define HPERR_ASCHAN_VID_WIDESYNCS  826
#define HPERR_ASCHAN_SYNC_SCANT     827
#define HPERR_ASCHAN_SYNC_HIDDEN    828
#define HPERR_ASCHAN_HSYNC_HIGH     829
#define HPERR_ASCHAN_OKAY_VSYNC     830
#define HPERR_ASCHAN_CT2_VSYNC      831
#define HPERR_ASCHAN_HSYNC_RANGE    832
#define HPERR_ASCHAN_HSYNC_SCANT    833
#define HPERR_ASCHAN_HSYNC_UNSTABLE 834
#define HPERR_ASCHAN_HSYNC_WANDER   835
#define HPERR_ASCHAN_HSYNC_FADE     836
#define HPERR_ASCHAN_VSYNC_BOUNCE   837
#define HPERR_ASCHAN_IMAGE_PHASE    838
#define HPERR_ASCHAN_IMAGE_HSWIDTH  839
#define HPERR_ASCHAN_OKAY_HSYNC     840
#define HPERR_ASCHAN_CT1_HSYNC      841
#define HPERR_ASCHAN_VSYNC_LONG     842
#define HPERR_ASCHAN_OKAY_CSYNC     843
#define HPERR_ASCHAN_SS_CT1HSYNC    844
#define HPERR_ASCHAN_SS_CT2VSYNC    845
#define HPERR_ASCHAN_SS_NOVIDEO     846
#define HPERR_ASCHAN_HIDEFPLUS      847
#define HPERR_ASCHAN_HIDEF4         848
#define HPERR_ASCHAN_HIDEF_I25      849
#define HPERR_ASCHAN_HIDEF_I50      850
#define HPERR_ASCHAN_HIDEFTYPE      851
#define HPERR_ASCHAN_NEEDSYNC       852
#define HPERR_ASCHAN_SYNCLESS       853
#define HPERR_ASCHAN_CT4GRAB        854
#define HPERR_ASCHAN_WIDTHLIMIT     855
#define HPERR_ASCHAN_MANYSYNCS      856
#define HPERR_ASCHAN_NO_VESA        860
#define HPERR_ASCHAN_HIDEF_I60      861
#define HPERR_ASCHAN_HIDEF_I75      862
#define HPERR_ASCHAN_HIDEF_IRGB25   863
#define HPERR_ASCHAN_HIDEF_IRGB50   864
#define HPERR_ASCHAN_HIDEF_IRGB75   865
#define HPERR_ASCHAN_HIDEF_IRGB165  866
#define HPERR_ASCHAN_HIDEF_IRGB200  867
#define HPERR_ASCHAN_HIDEF_IRGB170  868
#define HPERR_ASCHAN_HIDEF_IRGBI64_170  869
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM50 870
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM75 871
#define HPERR_ASCHAN_HIDEF_ACCUSTREAMVDR 872
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM205A 873
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM50A 874
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM75A 875
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM_170_PLUS 876
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM_75_PLUS 877
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM_50_PLUS 878
#define HPERR_ASCHAN_HIDEF_ACCUSTREAM_EXPRESS_170 879

/*
// IDEA Auto-SYNC Channel/Mode Elimination Codes.
*/
#define HPERR_ASMODE_SKIPPED        880
#define HPERR_ASMODE_HFREQ_LO       881
#define HPERR_ASMODE_HFREQ_HI       882
#define HPERR_ASMODE_HFREQ          883
#define HPERR_ASMODE_TTLCSYNC       884
#define HPERR_ASMODE_CT4GRAB        885
#define HPERR_ASMODE_HDPCSYNC       886
/*
// IDEA Auto-SYNC Pixel Detection error codes.
*/
#define HPERR_ASPD_SKIPPED          895
#define HPERR_ASPD_HFREQ            896
#define HPERR_ASPD_CONTRAST         897
#define HPERR_ASPD_NOPIXELS         898

#define HPERR_AS_LAST               898
/*
// ICI file parsing errors.
*/
#define HPERR_ICI_BOARDTYPE        1501
#define HPERR_ICI_KEYWORD          1502
#define HPERR_ICI_RANGE            1503
#define HPERR_ICI_FORM             1504
#define HPERR_ICI_TOKEN            1505
#define HPERR_ICI_LENGTH           1506
#define HPERR_ICI_NOFILE           1507
#define HPERR_ICI_EXTRA            1508
#define HPERR_ICI_NODATA           1509
#define HPERR_ICI_DOUTLIMIT        1510
#define HPERR_ICI_DSIGLIMIT        1511
#define HPERR_ICI_GENHSYNC         1512


#endif

